### ISSUE TITLE
Hi Chatterino I’m JameelPerkins 

### ISSUE THREAD

**Issue by Perkinsarmand32** [Chatterino/chatterino-browser-ext#103]
Asking can I connect my xbox series s to chatterino by using a capture card yes or no so I can stream online multiplayer with  my Xbox series s ?

**Comment by Perkinsarmand32** [comment]
please answer?

**Comment by Wissididom** [comment]
Chatterino is not an application for streaming media to a streaming platform. It is just a chat application for Twitch.

Also, this repo is just for the browser extension, which is pretty much abandoned.

**Comment by Perkinsarmand32** [comment]
Sent from my iPad I understand On Dec 21, 2024, at 4:08 pm, Wissididom ***@***.***> wrote:﻿
Chatterino is not an application for streaming media to a streaming platform. It is just a chat application for Twitch.
Also, this repo is just for the browser extension, which is pretty much abandoned.
