### ISSUE TITLE
Chatteriono browser extension not working with bbtv left chat enabled 

### ISSUE THREAD

**Issue by earlify** [Chatterino/chatterino-browser-ext#15]
Hi there,
sadly when I activate the chatterino browser extension while having the bttv left chat enabled the chat dows not move to the left. it just blocks my following list and the chat space is empty while saying
"Chatterino should be here ..." please fix. I love left chat. FeelsDankMan <3

Kind regards
Earl
![error](https://user-images.githubusercontent.com/64539544/80603990-6c1b9900-8a31-11ea-8185-ddb881301006.PNG)

**Comment by mfmarlow** [comment]
I fixed this in #19

**Comment by alazymeme** [comment]
@pajlada pls close
