### ISSUE TITLE
Chatterino: Unknown option `parent-window` error

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino-browser-ext#41]
![image](https://user-images.githubusercontent.com/12804673/94436400-bc18aa80-01df-11eb-8f6b-37af241d3cf0.png)

Occurs when opening a twitch channel

Chatterino Nightly 2.2.2 (commit b67e20d96, 27.09.2020) - Windows 10

**Comment by Electrolyte220** [comment]
Having the same issue, but this window only started appearing after updating to commit 42daac088. I'm running this on Win 10 and using Brave. Before updating, I was on commit 8123a4789 with no issues.

Also, disabling the extension from the tickbox does nothing, as clicking off of and back on the browser makes this show again. Disabling the extension from your browser's extension page seems to be a temp fix for now.

**Comment by dnsge** [comment]
From https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host-protocol:
> On Windows, the native messaging host is also passed a command line argument with a handle to the calling chrome native window: --parent-window=<decimal handle value>. This lets the native messaging host create native UI windows that are correctly focused.
