### ISSUE TITLE
Opera GX does not seem to be compatible with Chatterino

### ISSUE THREAD

**Issue by HypoCheese** [Chatterino/chatterino-browser-ext#44]
The browser is quite comfortable, and the move from Chrome was real easy (Chrome had far too many memory and CPU-consuming issues for me to even bother staying with it). However, my beloved Chatterino no longer works!

**Comment by alazymeme** [comment]
Duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/43

**Comment by cinemassacres** [comment]
should close this
