### ISSUE TITLE
Chatterino doesn't work with Alternate Player for Twitch.tv

### ISSUE THREAD

**Issue by killertofus** [Chatterino/chatterino-browser-ext#46]
opening the chat shows regular twitch chat without chatterino even when you have the browser addon installed
![q](https://user-images.githubusercontent.com/16343162/98415852-43f1a000-203b-11eb-9ca3-1059eb55476c.gif)

**Comment by ALazyMeme** [comment]
Alternate Player is different code to the native twitch player and therefore would break the extension. However I don't see a good enough reason that the code should be changed just for 1 extension. Suggest users use a better solution like streamlink instead.
