### ISSUE TITLE
Chatterino keeps crashing

### ISSUE THREAD

**Issue by juancalcetin** [Chatterino/chatterino-browser-ext#56]
After new update 2.3.0, Chatterino keeps crashing when trying to load chat on web extension, using Firefox.

**Comment by Felanbird** [comment]
@juancalcetin can you try 2.3.1 that was released today

**Comment by ALazyMeme** [comment]
Cannot reproduce, Chatterino 2.3.3 (commit c8c28d7f5)
Microsoft Edge Version 92.0.902.55

**Comment by ALazyMeme** [comment]
Also duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/56
