### ISSUE TITLE
"Chatterino should be here"

### ISSUE THREAD

**Issue by Nerxxy** [Chatterino/chatterino-browser-ext#59]
![image](https://user-images.githubusercontent.com/37718547/117518272-042e5580-af97-11eb-83dc-0cfe14900fb1.png)
is there a way to fix this?

**Comment by killertofus** [comment]
try clicking on that  and is this on

![](https://i.imgur.com/x4W4sOR.png)

**Comment by ALazyMeme** [comment]
This issue doesn't provide the relevant information to debug the issue at hand. Considering there's also been no response for a while, I think this should be closed.
