### ISSUE TITLE
chat is out of window

### ISSUE THREAD

**Issue by d4ncy** [Chatterino/chatterino-browser-ext#66]
for some reason the chat is out of window i just installed the extension
![11](https://user-images.githubusercontent.com/91439592/134828387-16ee4b56-e58a-44ea-9b55-2b215d50bac6.jpg)

![22](https://user-images.githubusercontent.com/91439592/134828389-c5e09915-89f6-4a18-a510-aabdfb187646.jpg)

**Comment by tray2daworm** [comment]
![image](https://user-images.githubusercontent.com/98297863/150718682-ef6bf772-ccea-4502-96b2-ed4edd341ed2.png)
Same for me even in fullscreen

**Comment by sando** [comment]
Reset your browser zoom to 100%, it'll fix it.

Duplicate of #65.

**Comment by ALazyMeme** [comment]
Duplicate of #65
