### ISSUE TITLE
settings not savings

### ISSUE THREAD

**Issue by Derasiel** [Chatterino/chatterino-browser-ext#67]
Hello,
I am using the 7tv version chatterino and the settings are not savings, only 2 channels out of 7-8 I added the first time are saved,, I have to enter my twitch token everytime I restart the software and add the others channels aswell, everything reset if I restart Chatterino.

**Comment by LosFarmosCTL** [comment]
Can you reproduce that in the normal version of chatterino?

Also, what operating system and what chatterino version/commit are you using?

**Comment by ALazyMeme** [comment]
This is not related to the browser extension. Please post your issue on the main repo: https://github.com/chatterino/chatterino2/
