### ISSUE TITLE
Message history not loading

### ISSUE THREAD

**Issue by lolishida** [Chatterino/chatterino-browser-ext#69]
my message history was working before but today it started saying service is unavailable ( error 500 ) which ive never seen before. is it from me or server sided? and if on my side how can i fix it?
![Screenshot_1](https://user-images.githubusercontent.com/84755023/150999036-07ce29d9-b22c-40fb-9d9d-53dd4c438cf2.png)

**Comment by zneix** [comment]
See chatterino/chatterino#3542, this is not Chatterino's issue itself. The error message says that service which is responsible for loading messages is dead. On another note, I contacted admin of said service, he's aware of the issue and will fix it as soon as he can.
