### ISSUE TITLE
What happened to the chatterino browser extension?

### ISSUE THREAD

**Issue by eie357** [Chatterino/chatterino-browser-ext#74]
I use microsoft edge, but it seems like the integrated browser extension was removed from the extension store? said something about the extension being unsafe and it was deleted or something. Anybody know where to find an alternative that isnt deleted? really love the extension and im hoping theres another version i can download since this one is gone for some reason.

**Comment by fourtf** [comment]
dup https://github.com/Chatterino/chatterino-browser-ext/issues/73
