### ISSUE TITLE
extension stopped working on Firefox Developer Edition

### ISSUE THREAD

**Issue by shahzebgit** [Chatterino/chatterino-browser-ext#77]
Hello,
I tried reinstalling both chatterino and extension, It's still not showing up the chat.
System:
Windows 10 Pro (Ver 21H2)
7tv Chatterino
Firefox Developer Edition 106.0b2 (64-bit)
![image](https://user-images.githubusercontent.com/51449693/191755848-039c6b65-b359-48e4-8f0e-55e31ea181e7.png)

**Comment by agsolbe2** [comment]
did you try selecting the chat box to see if it pops up?

**Comment by shahzebgit** [comment]
> did you try selecting the chat box to see if it pops up?

Oh, it's fixed now after the new update, I will close this now.
